title: Yongtai Yin
description: Ph.D. Student at CUHK
baseurl: ""
url: ""

# Navigation Links
navigation:
  - title: Home
    url: /
  - title: CV
    url: /cv/
  - title: Publications
    url: /publications/